### ISSUE TITLE
Ernie's UI Incompatible

### ISSUE THREAD

**Issue by nearlyNonexistent** [KayelGee/control-concealer#1]
Ernie's UI enhancement breaks the positioning of the icons; or at least the icons break positioning with Ernie's.

**Comment by nearlyNonexistent** [comment]
![image](https://user-images.githubusercontent.com/4041565/89071276-32f20e00-d32b-11ea-82b4-42872b2fd490.png)

**Comment by KayelGee** [comment]
yeah as I use mostly css to reposition everything this module currently isn't compatible with any module that does the same. I'll try to think of a better way for the next version.

**Comment by KayelGee** [comment]
Should be fixed in the next version.
