### ISSUE TITLE
All controls are un-hidden when any control is selected.

### ISSUE THREAD

**Issue by Doresain** [KayelGee/control-concealer#15]
Hey, great module!

I'm running v9. Editing controls works as expected, and they are successfully hidden. Once any other control is selected, however, all hidden controls are revealed.

https://user-images.githubusercontent.com/26096062/159151514-9f772ef1-6d09-4655-8fd0-ee0d02a4a2d6.mp4

**Comment by dhorkin** [comment]
Yeah, I have noticed this, as well. The left column seems to remember hide settings, but the right column doesn't.

**Comment by lucaspicerni** [comment]
I'm having the same issue. I'd like to suggest, as a solution for v9, abandon the dev and prod tabs and implementing keyboard shortcuts, to switch between the two. The configuration of what to show or hide could be done via module configuration. Thanks for your work so far!

**Comment by KayelGee** [comment]
Can you try the new vesion and see if it is fixed?

**Comment by lucaspicerni** [comment]
Perfect to me! Thank you!

**Comment by dhorkin** [comment]
It's worse than before for me. When you go into edit mode, right click makes it look like things will be hidden, but when you confirm your changes, the UI doesn't change at all - controls stay in the "white" mode rather than being hidden, and if you click another control tab, your changes are lost.

**Comment by lucaspicerni** [comment]
I had this same problem, bit with me it was incompatibility with the Narrator Tools module

**Comment by dhorkin** [comment]
> I had this same problem, bit with me it was incompatibility with the Narrator Tools module

I don't have that module, but I will see if another module is the issue later today.

**Comment by Doresain** [comment]
Seems to work for me now, but I haven't really tested all the permutations. Thanks for working on this.

**Comment by dhorkin** [comment]
appears to be a compatibility issue with Combat Carousel. I've disabled that for now, but would love for that to be fixed.

**Comment by KayelGee** [comment]
I'll close this issue because it was a module incompatibility which was fixed.
If the issue persists just open a new issue.
