### ISSUE TITLE
The module does not work with Combat Carousel activated.

### ISSUE THREAD

**Issue by Padhiver** [KayelGee/control-concealer#16]
Hi!
I wanted to test your great module, starting to have a few too many non-deactivatable tools, but it turns out that it seems to be incompatible with Combat Carrousel. I used Find the Culprit to find out why I couldn't save changes to the module, and it seems that with Combat Carousel enabled, your module just doesn't work anymore.

Edit : All latest version of Foundry, Combat Caroussel, Control Concealer ... And Dnd5e.

![image](https://user-images.githubusercontent.com/80126915/160436790-41c87d72-6d15-43e6-8572-a647ab235e3a.png)

Thank you !

**Comment by VaethConner** [comment]
I've been hoping this would be fixed for so long now.. Both of these are really great modules...

**Comment by dhorkin** [comment]
The fix for this was unbelievably simple. Wish I'd taken a look sooner. You can temporarily install from my repo if you want it sooner. I didn't bump the version number in case @KayelGee's system does that automatically when generating a release.

**Comment by KayelGee** [comment]
appreciate the PR @dhorkin I'll check it on monday

**Comment by matheusferreira** [comment]
waiting the revision about this. I found your module today and is a feature that I didn't know that I need when I dm using notebook (hiding ui for local gaming session). But I use Combat Carousel too.

**Comment by KayelGee** [comment]
Sorry for taking so long, covid actually knocked me out the week I wanted to look at @dhorkin PR. 
I'll push out the new version today with the fix.
