### ISSUE TITLE
Option to suppress "controls have changed" messages

### ISSUE THREAD

**Issue by dhorkin** [KayelGee/control-concealer#17]
I add/remove modules all the time. I get the controls have changed messages ALL THE TIME and it's super obnoxious. As DM, it's easy enough to click edit twice to make it go away, but I still have to dismiss these notifications to be able to do that. And then I have to log in as each player and do it for them, because my players aren't tech savvy enough to do this on their own.

It's a huge pain and it's totally unnecessary. If you found all the controls, why bother with these notifications? At the very least, please add a config option to hide this. Or prevent it from showing more than once, at least.

![image](https://user-images.githubusercontent.com/16787581/171931155-5af58830-b536-4c5e-9bda-15886d2311b2.png)

**Comment by KayelGee** [comment]
I agree it shouldn't spam these messages. When all controls have been found then I should just auto save the new controls(which should also suppress further messages).

**Comment by KayelGee** [comment]
In the new release the messages should only show up at most twice. When a mismatch is found and all controls are found then it will auto save the controls but still show a message that this has been done. 

If the messages keep on spamming, F5 should clear them.

I've also included a macro to copy the control settings from one user to multiple other users, so you should only need to setup one user and copy the settings to all other users in one go.
