### ISSUE TITLE
Unable to select the Develop tab

### ISSUE THREAD

**Issue by cwdean** [KayelGee/control-concealer#6]
Using Foundry VTT version 0.7.9 I am unable to select the Develop tab.  The Production tab and Toggle edit mode buttons work just fine, but selecting the Develop tab button does nothing.  So in essence the add-on still works, but not all functionality appears to be available.  Additionally, with Edit mode activated and attempting to hide some tabs from the sidebar, I am able to select a tab but the tab selected is one to the left of the tab that my mouse cursor is over.  Again, still functional but not quite right.

Is it possible to get this fixed soon?  I'm enjoying the add-on but don't want to fully enable for my players until this is working a bit cleaner.

**Comment by KayelGee** [comment]
thanks for noticing
fixed in 1.1.1
